#!/usr/bin/env bash
# Configures an Ubuntu server to modify the IP addresses for localhost and facebook.com.

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
