#!/usr/bin/env bash
# Run Apache as designated container.

echo "Hello Holberton" >> /etc/apache2.conf
service apsche2 strat#!/usr/bin/env bash
# Run Apache as designated container.

echo "Hello Holberton" >> /etc/apache2.conf
service apsche2 strat
